const ITEMS = [
  { name: "Chicken Fried Rice", price: "#300" },
  { name: "Coconut Rice", price: "#250" },
  { name: "Fried Rice", price: "#250" },
  { name: "Fruit parfait", price: "#1600" },
  { name: "Jollof Rice", price: "#250" },
  { name: "Ofada Rice", price: "#200" },
  { name: "Ofade Sauce", price: "#400" },
  { name: "Jambalaya Rice", price: "#300" },
  { name: "Plantain", price: "#200" },
  { name: "Eba", price: "#150" },
  { name: "Semo", price: "#200" },
  { name: "Pounded yam", price: "#200" },
  { name: "Amala", price: "#200" },
  { name: "Egusi", price: "#350" },
  { name: "Efo riro", price: "#350" },
  { name: "Grilled Chicken", price: "#1,100" },
  { name: "Fried Chicken", price: "#1,100" },
  { name: "Beef", price: "#400" },
  { name: "Cat Fish", price: "#700" },
  { name: "Panla Fish", price: "#400" },
  { name: "Yam Pottage", price: "#200" },
  { name: "Shawama", price: "#1,500" },
  { name: "Doughnut", price: "#200" },
  { name: "Scotch Egg", price: "#250" },
  { name: "Sausage Roll", price: "#200" },
  { name: "Chicken pie", price: "#400" },
  { name: "Meat Pie", price: "#390" },
  { name: "Butter Bread", price: "#600" },
  { name: "Ice cream 120ml", price: "#210" },
  { name: "Ice cream 220ml", price: "#350" },
  { name: "Ice cream 500ml", price: "#900" },
  { name: "Coke", price: "#200" },
  { name: "Fanta", price: "#200" },
  { name: "Sprite", price: "#200" },
  { name: "Pepsi", price: "#200" },
  { name: "Mirinda", price: "#200" },
  { name: "Bottle Water", price: "#150" },
  { name: "5 Alive pulpy", price: "#250" },
  { name: "5 Alive pulpy (big)", price: "#600" },
  { name: "Chivita", price: "#800" },
  { name: "Hollandia Yoghurt", price: "#1000" },
  { name: "Vita Milk", price: "#700" },
  { name: "Fresh Yo Big", price: "#600" },
  { name: "Asun", price: "#500" },
  { name: "Barbecue Fish", price: "#1,500" },
  { name: "Cinnamon Bread", price: "#750" },
  { name: "Pepper Gizzard", price: "#800" },
  { name: "Pepper Snail", price: "#1,800" },
  { name: "Buns", price: "#120" },
  { name: "Moimoi", price: "#250" },
  { name: "Combo Chicken", price: "#600" },
  { name: "Coleslaw", price: "#200" },
];

module.exports = ITEMS;
