const ITEMS = [
  { name: "Chicken Fried Rice", price: "#250" },
  { name: "Coconut Rice", price: "#250" },
  { name: "Fried Rice", price: "#200" },
  { name: "Fruit parfait", price: "#1600" },
  { name: "Jollof Rice", price: "#200" },
  { name: "Ofada Rice", price: "#600" },
  { name: "Ofade Sauce", price: "#400" },
  { name: "Jambalaya Rice", price: "#250" },
  { name: "Pasta", price: "#400"},
  { name: "Plantain", price: "#200" },
  { name: "Eba", price: "#150" },
  { name: "Extra Eba", price: "#100" },
  { name: "Plate of Eba", price: "#700" },
  { name: "Semo", price: "#200" },
  { name: "Extra Semo", price: "#200" },
  { name: "Plate of Semo", price: "#900" },
  { name: "Pounded yam", price: "#200" },
  { name: "Amala", price: "#200" },
  { name: "Extra Amala", price: "#200" },
  { name: "Plate of Amala", price: "#900" },
  { name: "Egusi", price: "#250" },
  { name: "Efo riro", price: "#250" },
  { name: "Grilled Chicken", price: "#900" },
  { name: "Fried Chicken", price: "#900" },
  { name: "Beef", price: "#400" },
  { name: "Ponmo", price: "#100" },
  { name: "Ogunfe", price: "#500" },
  { name: "Tinu Eran", price: "#400"},
  { name: "Cat Fish", price: "#700" },
  { name: "Panla Fish", price: "#400" },
  { name: "Yam Pottage", price: "#200" },
  { name: "Shawama", price: "#1,500" },
  { name: "Doughnut", price: "#150" },
  { name: "Scotch Egg", price: "#250" },
  { name: "Sausage Roll", price: "#200" },
  { name: "Chicken pie", price: "#400" },
  { name: "Meat Pie", price: "#400" },
  { name: "Butter Bread", price: "#600" },
  { name: "Ice cream 120ml", price: "#270" },
  { name: "Ice cream 220ml", price: "#380" },
  { name: "Ice cream 500ml", price: "#900" },
  { name: "Coke", price: "#200" },
  { name: "COCACOLA 35cl", price: "#150"},
  { name: "COCACOLA 50cl", price: "#250"},
  { name: "COCACOLA MAMA", price: "#350"},
  { name: "Fanta", price: "#200" },
  { name: "Sprite", price: "#200" },
  { name: "Pepsi", price: "#200" },
  { name: "Mirinda", price: "#200" },
  { name: "Bottle Water", price: "#150" },
  { name: "5 Alive Small", price: "#300" },
  { name: "5 Alive", price: "#600" },
  { name: "Chivita", price: "#800" },
  { name: "Hollandia Yoghurt", price: "#1000" },
  { name: "Vital Milk", price: "#750" },
  { name: "Fresh Yo Big", price: "#650" },
  { name: "Fresh Yo Small", price: "#350" },
  { name: "Maltina", price: "#300" },
  { name: "Asun", price: "#500" },
  { name: "Barbecue Fish", price: "#1,500" },
  { name: "Cinnamon Bread", price: "#750" },
  { name: "Pepper Gizzard", price: "#800" },
  { name: "Gizzard", price: "#400" },
  { name: "Pepper Snail", price: "#1,800" },
  { name: "Buns", price: "#100" },
  { name: "Moimoi", price: "#250" },
  { name: "Combo Chicken", price: "#500" },
  { name: "Coleslaw", price: "#200" },
];

module.exports = ITEMS;
